name: Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test coverage
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install pytest-cov
        pip install .
    - name: Run tests and collect coverage
      run: pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=src/codecov_demo --cov=tests --cov-report=xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3.1.1
