name: Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test coverage
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install requirements
      run: pip install .
    - name: Run tests and collect coverage
      run: pytest --cov=./ --cov-report=xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3.1.1
